In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [4]:
pip install pandas scikit-learn xgboost catboost


In [29]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from sklearn.tree import DecisionTreeClassifier

In [10]:

data = pd.read_csv("/Users/hs/AIML/Capstone_Colab/data.csv")

In [11]:
data.head()

step      type    amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0     1   PAYMENT   9839.64  C1231006815       170136.0       160296.36   
1     1   PAYMENT   1864.28  C1666544295        21249.0        19384.72   
2     1  TRANSFER    181.00  C1305486145          181.0            0.00   
3     1  CASH_OUT    181.00   C840083671          181.0            0.00   
4     1   PAYMENT  11668.14  C2048537720        41554.0        29885.86   

      nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0  M1979787155             0.0             0.0        0               0  
1  M2044282225             0.0             0.0        0               0  
2   C553264065             0.0             0.0        1               0  
3    C38997010         21182.0             0.0        1               0  
4  M1230701703             0.0             0.0        0               0

In [12]:
# Remove irrelevant columns
data = data.drop(['step', 'nameOrig', 'nameDest'], axis=1)


In [13]:
X = data.drop(['isFraud', 'isFlaggedFraud'], axis=1)
y = data['isFraud']

In [14]:
X.head()

type    amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
0   PAYMENT   9839.64       170136.0       160296.36             0.0   
1   PAYMENT   1864.28        21249.0        19384.72             0.0   
2  TRANSFER    181.00          181.0            0.00             0.0   
3  CASH_OUT    181.00          181.0            0.00         21182.0   
4   PAYMENT  11668.14        41554.0        29885.86             0.0   

   newbalanceDest  
0             0.0  
1             0.0  
2             0.0  
3             0.0  
4             0.0

In [15]:
X.replace(to_replace=['CASH_OUT', 'PAYMENT', 'CASH_IN', 'TRANSFER', 'DEBIT'],value=[1,2,3,4,5],inplace=True)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=4)

In [18]:

dt_model=DecisionTreeClassifier()
dt_model.fit(X_train, y_train)
dt_predictions=dt_model.predict(X_test)

In [19]:
xgb_model = XGBClassifier()
X_train_xgb = pd.get_dummies(X_train, columns=['type'], drop_first=True)
X_test_xgb = pd.get_dummies(X_test, columns=['type'], drop_first=True)
xgb_model.fit(X_train_xgb, y_train)
xgb_predictions = xgb_model.predict(X_test_xgb)

In [20]:
catboost_model = CatBoostClassifier(cat_features=['type'])
catboost_model.fit(X_train, y_train)
catboost_predictions = catboost_model.predict(X_test)

Learning rate set to 0.39419
0:	learn: 0.0424501	total: 964ms	remaining: 16m 3s
1:	learn: 0.0099977	total: 1.72s	remaining: 14m 19s
2:	learn: 0.0036909	total: 2.46s	remaining: 13m 39s
3:	learn: 0.0025686	total: 3.23s	remaining: 13m 23s
4:	learn: 0.0023276	total: 3.97s	remaining: 13m 9s
5:	learn: 0.0019834	total: 4.72s	remaining: 13m 1s
6:	learn: 0.0018487	total: 5.46s	remaining: 12m 54s
7:	learn: 0.0017594	total: 6.09s	remaining: 12m 34s
8:	learn: 0.0017053	total: 6.9s	remaining: 12m 39s
9:	learn: 0.0016665	total: 7.58s	remaining: 12m 30s
10:	learn: 0.0016288	total: 8.29s	remaining: 12m 25s
11:	learn: 0.0015997	total: 9.05s	remaining: 12m 25s
12:	learn: 0.0015647	total: 9.76s	remaining: 12m 20s
13:	learn: 0.0015221	total: 10.4s	remaining: 12m 16s
14:	learn: 0.0015040	total: 11.3s	remaining: 12m 20s
15:	learn: 0.0014899	total: 12.1s	remaining: 12m 21s
16:	learn: 0.0014666	total: 12.7s	remaining: 12m 16s
17:	learn: 0.0014365	total: 13.5s	remaining: 12m 15s
18:	learn: 0.0014209	total: 14.

In [22]:
xgb_accuracy = accuracy_score(y_test, xgb_predictions)
catboost_accuracy = accuracy_score(y_test, catboost_predictions)
dt_accuracy = accuracy_score(y_test, dt_predictions)

In [23]:
xgb_conf_matrix = confusion_matrix(y_test, xgb_predictions)
xgb_precision = precision_score(y_test, xgb_predictions)
xgb_recall = recall_score(y_test, xgb_predictions)

In [24]:
catboost_conf_matrix = confusion_matrix(y_test, catboost_predictions)
catboost_precision = precision_score(y_test, catboost_predictions)
catboost_recall = recall_score(y_test, catboost_predictions)

In [26]:
dt_conf_matrix = confusion_matrix(y_test, dt_predictions)
dt_precision = precision_score(y_test, dt_predictions)
dt_recall = recall_score(y_test, dt_predictions)

In [32]:
xgb_f1_score = f1_score(y_test, xgb_predictions)
catboost_f1_score = f1_score(y_test, catboost_predictions)
dt_f1_score = f1_score(y_test, dt_predictions)

In [33]:
print("XGBoost Metrics:")
print(f'Accuracy: {xgb_accuracy}')
print(f'Confusion Matrix:\n{xgb_conf_matrix}')
print(f'Precision: {xgb_precision}')
print(f'Recall: {xgb_recall}')
print(f'F1 Score: {xgb_f1_score}')

print("\n CatBoost Metrics:")
print(f'Accuracy: {catboost_accuracy}')
print(f'Confusion Matrix:\n{catboost_conf_matrix}')
print(f'Precision: {catboost_precision}')
print(f'Recall: {catboost_recall}')
print(f'F1 Score: {catboost_f1_score}')

print("\n Decision Metrics:")
print(f'Accuracy: {dt_accuracy}')
print(f'Confusion Matrix:\n{dt_conf_matrix}')
print(f'Precision: {dt_precision}')
print(f'Recall: {dt_recall}')
print(f'F1 Score: {dt_f1_score}')

XGBoost Metrics:
Accuracy: 0.9996542304899554
Confusion Matrix:
[[1270796      54]
 [    386    1288]]
Precision: 0.9597615499254843
Recall: 0.7694145758661888
F1 Score: 0.8541114058355438

 CatBoost Metrics:
Accuracy: 0.9996487296113865
Confusion Matrix:
[[1270728     122]
 [    325    1349]]
Precision: 0.9170632222977566
Recall: 0.8058542413381123
F1 Score: 0.8578696343402226

 Decision Metrics:
Accuracy: 0.9997406728674666
Confusion Matrix:
[[1270716     134]
 [    196    1478]]
Precision: 0.9168734491315137
Recall: 0.8829151732377539
F1 Score: 0.8995739500912965
